инкремент 13: повтор запросов клиента, повтор запросов к базе
NikolayStrekalov/vigilant-octo-waddle pull request #13
Opened 2024-06-11 16:43 UTC by NikolayStrekalov

1. На агенте повторяем запрос к серверу
2. На сервере повторяем запросы к постгресу.

2024-06-17 21:36 UTC, avhitrov requested changes
Есть пара недочетов в работе агента, отметил комментариями к ПР.  В остальном - отличное решение.

2024-06-17 21:36 UTC, avhitrov commented on internal/agent/report.go
> +const maxRequestAttempts = 4
По ТЗ вроде 3 попытки

2024-06-17 21:36 UTC, avhitrov commented on internal/agent/report.go
> +func sendStatJSON(m easyjson.Marshaler, toURL string) {
```suggestion
func sendStatJSON(m easyjson.Marshaler, toURL string) error {
```

2024-06-17 21:36 UTC, avhitrov commented on internal/agent/report.go
>  		PollCount = 0
По хорошему, счетчик надо сбрасывать только после успешной отправки статистики. Имеет смысл либо отправку статистики перенести выше сброса счетчика и запускать не в отдельной горутине, а прямо в этой горутине. Либо сделать отдельный блок Lock-Unlock для сброса счетчика, поместить его ниже sendStatJSON и все равно запускать  отправку в этой же горутине. Потому как ловить ошибки из горутины - довольно громоздкая по организации процедура, связанная с передачей и последубщим чтением каналов. Пример: https://go.dev/play/p/9oW38hPnkbU

2024-06-17 21:36 UTC, avhitrov commented on internal/server/app.go
> +		logger.Info("error creating storage:", err)
```suggestion
		logger.Fatal("error creating storage:", err)
```
В этом случае можно смело и с грохотом падать.

2024-06-18 17:57 UTC, NikolayStrekalov commented on internal/agent/report.go
> +const maxRequestAttempts = 4
3 повторные попытки, всего 4

> Количество повторов должно быть ограничено тремя дополнительными попытками.

2024-06-18 17:58 UTC, NikolayStrekalov commented on internal/agent/report.go
> +func sendStatJSON(m easyjson.Marshaler, toURL string) {
fixed

2024-06-18 17:59 UTC, NikolayStrekalov commented on internal/agent/report.go
>  		PollCount = 0
Стал возвращать при неудаче PollCount-ы из обновления. Делается в этой же горутине, Заменил отсчет времени на тикер.

2024-06-18 18:02 UTC, NikolayStrekalov commented on internal/server/app.go
> +		logger.Info("error creating storage:", err)
По заданию у сервера существует метод `/ping`, который работает при невозможности инициализации стораджа, поэтому просто упасть не можем.

По-хорошему, тут сделать повторные инициализации, но теста на это нет, в заданиях про это не говорится ничего, поэтому я ограничился TODO в комментарии чуть выше по коду.

2024-06-18 18:04 UTC, NikolayStrekalov commented
Поправил отправку агентом статистик. Теперь PollCount-ы не теряются.

2024-06-23 21:49 UTC, avhitrov approved these changes
Аппрув, что назывется, с помарками. Надеюсь, я объяснил, почему не следует стартовать неинициализированный сервис. Ну и про ticker - есть комментарий.

2024-06-23 21:49 UTC, avhitrov commented on internal/agent/report.go
> +	ticker := time.NewTicker(time.Duration(Config.ReportInterval) * time.Second)
```
defer ticker.Stop()
```
https://pkg.go.dev/time#NewTicker

2024-06-23 21:49 UTC, avhitrov commented on internal/server/app.go
> +		logger.Info("error creating storage:", err)
Неверное понимание задания. Метод ping нужен для мониторинга состояния соединения. Но если DSN указан неверно или сервер сразу недоступен, лучше не пытаться поднимать сервис (явно зависимый от БД). Потому как разрыв соединения - это диагностируемая (и устраняемая) проблема, а хендлер БД, инициализированный в nil - это поток паник в логах и необходимость все равно перезапустить сервер для инициализации соединения.

2024-06-24 09:47 UTC, NikolayStrekalov commented on internal/server/app.go
> +		logger.Info("error creating storage:", err)
@avhitrov  Указанная реализация  противоречит тесту десятого инкремента https://github.com/Yandex-Practicum/go-autotests/blob/main/cmd/metricstest/iteration10b_test.go

2024-06-24 09:54 UTC, merged