инкремент 9: сохранение метрик в файл
NikolayStrekalov/vigilant-octo-waddle pull request #9
Opened 2024-05-28 00:44 UTC by NikolayStrekalov

Сервер с заданной периодичностью сохраняяет текущие значения метрик на диск в указанный файл, а на старте — опционально загружает сохранённые ранее значения. 
При штатном завершении сервера все накопленные данные с.охраняются.

2024-06-02 10:30 UTC, avhitrov requested changes
1. Небольшое замечание относительно использования os.Exit в горутинах
2. Предлагаю сброс состояния данных в файл при синхронной записи переместить на уровень стораджа. Во-первых, таким образом удастся избежать гонок второго порядка (https://t.me/bushigo/35), а во-вторых, вынесет логику работы со стораджем за пределы хендлера и уменьшит связность между моудлями. В дальнейшем это все равно придется сделать, так как будет добавлен третий сторадж с аналогичным интерфейсом.

2024-06-02 10:30 UTC, avhitrov commented on internal/server/app.go
> +		os.Exit(0)
Выход из приложения, пусть и с кодом 0, осуществленный в горутине, очень вреден, так как порвет все остальные горутины и defer-ы. Если что-то не успеет завершиться в основной ветке, оно будет просто прибито. Лучше просто дать отработать горутине и выйти через стандартное окончание main().

2024-06-03 08:30 UTC, NikolayStrekalov commented
Изменения по замечаниям:
1. Изменил поведение при закрытии сервера.
2. Перенес синхронизацию в сторадж. Гонки были добавлены намерено, сохранены в текущей версии, ниже объяснения.

Далее приведу логику, которая определяет наличие гонок и почему это "фича".

Есть задание инкремента 7:
> Передавать метрики нужно через POST update/. В теле ответа отправляйте JSON той же структуры с актуальным (изменённым) значением Value

Из задания следует, что допускается гонка между записью и чтением/отправкой значения метрики, поскольку написано "актуальное значение".  (Смысл в  двусмысленной интерпретации "с актуальным (изменённым) значением", которую допускает формулировка задания)

Задание инкремента 9:
> (по умолчанию 300 секунд, значение 0 делает запись синхронной).

Допустим, что такая формулировка подразумевает, что сервер дает клиенту гарантию "сервер записывает в файл то значение, которое присылает клиент". Что это значит для клиента, если в ответ клиент получает значение, не соответствующее его запросу (что допускается формулировкой инкремента 7)? Он не может использовать полученное значение, потому что на полученное значение гарантия сервера не распространяется. Поэтому я формулирую требование синхронной записи так: "сервер сохранил значение, которое клиент получил в ответе".

Теперь у нас есть две реализации, которые обеспечивают сформулированную гарантию: действительно синхронная запись после обновления в памяти и текущая реализация. Особенность текущего сформулированного интерфейса сервера такова, что клиент не различит эти реализации. То есть по своим запросам, логам сервера и дампу. (Например, клиент мог бы отличать два случая, если бы были специфицированы некоторые ошибки, но в текущем задании этого нет).

Поэтому мной предполагается, что текущая реализация удовлетворяет условию заданий. Кроме того, текущая реализация позволяет делать больше запросов на чтение, поскольку время лока на запись меньше.

2024-06-05 21:43 UTC, avhitrov approved these changes
Все ок, реализация годная.

2024-06-06 05:51 UTC, merged